-- enum 컬럼(provider, role)에는 CHECK 제약을 두지 않는다. 값 검증은 Java enum 이 하고,
-- enum 값을 추가할 때마다 제약을 바꾸는 마이그레이션이 필요해지는 것을 피한다

CREATE TABLE member
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         TIMESTAMP(6) NOT NULL,
    updated_at         TIMESTAMP(6) NOT NULL,
    email              VARCHAR(255),
    nickname           VARCHAR(100) NOT NULL,
    password           VARCHAR(60),
    profile_image_url  VARCHAR(500),
    provider           VARCHAR(20)  NOT NULL,
    provider_member_id VARCHAR(255) NOT NULL,
    role               VARCHAR(20)  NOT NULL,
    deleted_at         TIMESTAMP(6),
    CONSTRAINT uk_member_provider_provider_member_id UNIQUE (provider, provider_member_id)
);

CREATE INDEX idx_member_deleted_at ON member (deleted_at);

CREATE TABLE refresh_token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  BIGINT       NOT NULL,
    token_hash VARCHAR(64)  NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    session_id VARCHAR(36),
    CONSTRAINT uk_refresh_token_token_hash UNIQUE (token_hash),
    CONSTRAINT uk_refresh_token_session_id UNIQUE (session_id)
);

CREATE INDEX idx_refresh_token_member_id ON refresh_token (member_id);

CREATE TABLE email_verification
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    code          VARCHAR(6)   NOT NULL,
    sent_at       TIMESTAMP(6) NOT NULL,
    expires_at    TIMESTAMP(6) NOT NULL,
    attempt_count INTEGER      NOT NULL,
    verified_at   TIMESTAMP(6),
    CONSTRAINT uk_email_verification_email UNIQUE (email)
);

CREATE TABLE member_interest_car
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    member_id     BIGINT       NOT NULL,
    car_model_id  BIGINT       NOT NULL,
    display_order INTEGER      NOT NULL,
    CONSTRAINT uk_member_interest_car_member_id_car_model_id UNIQUE (member_id, car_model_id)
);

CREATE INDEX idx_member_interest_car_member_id ON member_interest_car (member_id);
