-- MVP 기능(차종 마스터, 보유 차량, 부품, 이미지 업로드, 게시물, 위시리스트, 차단, 신고, 비밀번호 재설정, 이용 정지) 스키마.
-- 기존 테이블과 같이 도메인 간 FK 는 두지 않는다. 회원 데이터 정리는 MemberPurgedEvent 리스너가 맡는다

-- 부품·브랜드 검색에서 오타·부분 일치를 찾기 위한 trigram 유사도
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 이메일 인증을 회원가입과 비밀번호 재설정에 함께 쓴다. 같은 이메일이라도 용도별로 한 줄씩 둔다
ALTER TABLE email_verification ADD COLUMN purpose VARCHAR(20) NOT NULL DEFAULT 'SIGNUP';
ALTER TABLE email_verification ALTER COLUMN purpose DROP DEFAULT;
ALTER TABLE email_verification DROP CONSTRAINT uk_email_verification_email;
ALTER TABLE email_verification ADD CONSTRAINT uk_email_verification_email_purpose UNIQUE (email, purpose);

ALTER TABLE member ADD COLUMN suspended_until TIMESTAMP(6);

CREATE TABLE car_model
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manufacturer  VARCHAR(50)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    display_order INTEGER      NOT NULL,
    CONSTRAINT uk_car_model_manufacturer_name UNIQUE (manufacturer, name)
);

CREATE TABLE car_generation
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_model_id BIGINT       NOT NULL,
    code         VARCHAR(50)  NOT NULL,
    name         VARCHAR(100) NOT NULL,
    start_year   INTEGER      NOT NULL,
    end_year     INTEGER,
    CONSTRAINT uk_car_generation_car_model_id_code UNIQUE (car_model_id, code)
);

CREATE TABLE car_trim
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_generation_id BIGINT       NOT NULL,
    name              VARCHAR(100) NOT NULL,
    CONSTRAINT uk_car_trim_car_generation_id_name UNIQUE (car_generation_id, name)
);

CREATE TABLE owned_car
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP(6) NOT NULL,
    updated_at        TIMESTAMP(6) NOT NULL,
    member_id         BIGINT       NOT NULL,
    car_model_id      BIGINT       NOT NULL,
    car_generation_id BIGINT       NOT NULL,
    car_trim_id       BIGINT,
    model_year        INTEGER,
    build_direction   VARCHAR(20)
);

CREATE INDEX idx_owned_car_member_id ON owned_car (member_id);

CREATE TABLE brand
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    name            VARCHAR(50)  NOT NULL,
    normalized_name VARCHAR(50)  NOT NULL,
    CONSTRAINT uk_brand_normalized_name UNIQUE (normalized_name)
);

CREATE INDEX idx_brand_name ON brand USING gin (name gin_trgm_ops);

-- 브랜드 없는 부품(자작 등)도 이름이 같으면 하나로 본다
CREATE TABLE part
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    brand_id        BIGINT,
    name            VARCHAR(100) NOT NULL,
    normalized_name VARCHAR(100) NOT NULL,
    category        VARCHAR(20)  NOT NULL,
    CONSTRAINT uk_part_brand_id_normalized_name UNIQUE NULLS NOT DISTINCT (brand_id, normalized_name)
);

CREATE INDEX idx_part_name ON part USING gin (name gin_trgm_ops);

CREATE TABLE uploaded_image
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    member_id   BIGINT       NOT NULL,
    storage_key VARCHAR(100) NOT NULL,
    url         VARCHAR(500) NOT NULL,
    width       INTEGER,
    height      INTEGER,
    attached    BOOLEAN      NOT NULL,
    CONSTRAINT uk_uploaded_image_storage_key UNIQUE (storage_key)
);

CREATE INDEX idx_uploaded_image_member_id ON uploaded_image (member_id);
CREATE INDEX idx_uploaded_image_attached_created_at ON uploaded_image (attached, created_at);

CREATE TABLE post
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP(6) NOT NULL,
    updated_at        TIMESTAMP(6) NOT NULL,
    member_id         BIGINT       NOT NULL,
    car_model_id      BIGINT       NOT NULL,
    car_generation_id BIGINT       NOT NULL,
    car_trim_id       BIGINT,
    model_year        INTEGER,
    build_direction   VARCHAR(20)  NOT NULL,
    content           VARCHAR(2000),
    status            VARCHAR(20)  NOT NULL,
    part_count        INTEGER      NOT NULL
);

CREATE INDEX idx_post_member_id ON post (member_id);
CREATE INDEX idx_post_status_car_model_id ON post (status, car_model_id);

CREATE TABLE post_image
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id           BIGINT       NOT NULL REFERENCES post (id),
    uploaded_image_id BIGINT       NOT NULL,
    url               VARCHAR(500) NOT NULL,
    width             INTEGER,
    height            INTEGER,
    display_order     INTEGER      NOT NULL,
    CONSTRAINT uk_post_image_uploaded_image_id UNIQUE (uploaded_image_id)
);

CREATE INDEX idx_post_image_post_id ON post_image (post_id);

CREATE TABLE post_part_tag
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_image_id BIGINT           NOT NULL REFERENCES post_image (id),
    part_id       BIGINT           NOT NULL,
    x             DOUBLE PRECISION NOT NULL,
    y             DOUBLE PRECISION NOT NULL
);

CREATE INDEX idx_post_part_tag_post_image_id ON post_part_tag (post_image_id);

CREATE TABLE wishlist_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    member_id  BIGINT       NOT NULL,
    part_id    BIGINT       NOT NULL,
    CONSTRAINT uk_wishlist_item_member_id_part_id UNIQUE (member_id, part_id)
);

CREATE TABLE member_block
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    blocker_id BIGINT       NOT NULL,
    blocked_id BIGINT       NOT NULL,
    CONSTRAINT uk_member_block_blocker_id_blocked_id UNIQUE (blocker_id, blocked_id)
);

CREATE INDEX idx_member_block_blocked_id ON member_block (blocked_id);

CREATE TABLE report
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMP(6) NOT NULL,
    updated_at       TIMESTAMP(6) NOT NULL,
    reporter_id      BIGINT       NOT NULL,
    target_type      VARCHAR(20)  NOT NULL,
    target_id        BIGINT       NOT NULL,
    target_member_id BIGINT       NOT NULL,
    reason           VARCHAR(30)  NOT NULL,
    detail           VARCHAR(500),
    status           VARCHAR(20)  NOT NULL,
    action           VARCHAR(20),
    resolved_by      BIGINT,
    resolved_at      TIMESTAMP(6),
    CONSTRAINT uk_report_reporter_id_target_type_target_id UNIQUE (reporter_id, target_type, target_id)
);

CREATE INDEX idx_report_status ON report (status);
CREATE INDEX idx_report_target_member_id ON report (target_member_id);
