-- 기능 명세(P1)에 맞춘 스키마 변경. V3 는 이미 배포 브랜치에 올라가 있어 고치지 않고 여기서 바꾼다.
-- 구조가 크게 바뀐 보유 차량·사진 업로드·게시물·위시리스트 테이블은 출시 전 개발 데이터만 있으므로 지우고 다시 만든다

-- 이메일 인증: 코드를 확인하면 verificationToken 을 발급하고 해시만 저장한다
ALTER TABLE email_verification ADD COLUMN verification_token_hash VARCHAR(64);

ALTER TABLE member ADD COLUMN status_message VARCHAR(50);

-- 닉네임 중복 불가. 이미 겹친 닉네임은 뒤에 회원 id 를 붙여 풀어 둔다
UPDATE member m
SET nickname = LEFT(m.nickname, 12 - LENGTH(m.id::TEXT)) || m.id
WHERE EXISTS (SELECT 1 FROM member o WHERE o.nickname = m.nickname AND o.id < m.id);
ALTER TABLE member ADD CONSTRAINT uk_member_nickname UNIQUE (nickname);

-- 차종 마스터: manufacturer -> brand, 핵심 계열·이미지·숨김 추가, 세대 이름은 쓰지 않는다
ALTER TABLE car_model RENAME COLUMN manufacturer TO brand;
ALTER TABLE car_model RENAME CONSTRAINT uk_car_model_manufacturer_name TO uk_car_model_brand_name;
ALTER TABLE car_model ADD COLUMN is_core BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE car_model ALTER COLUMN is_core DROP DEFAULT;
ALTER TABLE car_model ADD COLUMN image_url VARCHAR(500);
ALTER TABLE car_model ADD COLUMN hidden BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE car_model ALTER COLUMN hidden DROP DEFAULT;
ALTER TABLE car_generation DROP COLUMN name;

-- 부품: 대소문자·공백·하이픈을 무시한 이름으로 검색하고, 확인 대기 상태와 사용 수를 둔다
DROP INDEX idx_brand_name;
CREATE INDEX idx_brand_normalized_name ON brand USING gin (normalized_name gin_trgm_ops);
DROP INDEX idx_part_name;
CREATE INDEX idx_part_normalized_name ON part USING gin (normalized_name gin_trgm_ops);
ALTER TABLE part ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'PENDING';
ALTER TABLE part ALTER COLUMN status DROP DEFAULT;
ALTER TABLE part ADD COLUMN use_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE part ALTER COLUMN use_count DROP DEFAULT;

-- 관리자 합치기로 사라진 부품 이름이 별칭으로 남는다. 검색은 별칭도 찾는다
CREATE TABLE part_alias
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id         BIGINT       NOT NULL,
    name            VARCHAR(150) NOT NULL,
    normalized_name VARCHAR(150) NOT NULL,
    CONSTRAINT uk_part_alias_part_id_normalized_name UNIQUE (part_id, normalized_name)
);

CREATE INDEX idx_part_alias_normalized_name ON part_alias USING gin (normalized_name gin_trgm_ops);

-- 차종별 부품 사용 수. 부품 검색에서 같은 차종에 자주 달린 부품을 위로 올린다
CREATE TABLE part_car_model_usage
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id      BIGINT  NOT NULL,
    car_model_id BIGINT  NOT NULL,
    use_count    INTEGER NOT NULL,
    CONSTRAINT uk_part_car_model_usage_part_id_car_model_id UNIQUE (part_id, car_model_id)
);

-- 신고: 사유 값을 명세에 맞추고, 상세 300자, 관리자 목록은 대상별로 묶어 본다
UPDATE report SET reason = 'INAPPROPRIATE' WHERE reason IN ('ABUSE', 'SEXUAL', 'IMPERSONATION');
UPDATE report SET detail = LEFT(detail, 300) WHERE LENGTH(detail) > 300;
ALTER TABLE report ALTER COLUMN detail TYPE VARCHAR(300);
DROP INDEX idx_report_status;
CREATE INDEX idx_report_status_target_type_target_id ON report (status, target_type, target_id);

DROP TABLE wishlist_item;
DROP TABLE post_part_tag;
DROP TABLE post_image;
DROP TABLE post;
DROP TABLE uploaded_image;
DROP TABLE owned_car;

-- 보유 차량: 트림 단위, 연식 필수, 별칭, 지금 타는 차(OWNED)·이전 차량(PAST)
CREATE TABLE owned_car
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP(6) NOT NULL,
    updated_at        TIMESTAMP(6) NOT NULL,
    member_id         BIGINT       NOT NULL,
    car_model_id      BIGINT       NOT NULL,
    car_generation_id BIGINT       NOT NULL,
    car_trim_id       BIGINT       NOT NULL,
    model_year        INTEGER      NOT NULL,
    build_style       VARCHAR(20),
    nickname          VARCHAR(20),
    status            VARCHAR(20)  NOT NULL
);

CREATE INDEX idx_owned_car_member_id ON owned_car (member_id);

-- 업로드 URL 을 발급한 사진 키. 파일이 올라오면 UPLOADED, 게시물·프로필에 쓰이면 ATTACHED
CREATE TABLE uploaded_image
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    member_id    BIGINT       NOT NULL,
    image_key    VARCHAR(100) NOT NULL,
    content_type VARCHAR(30)  NOT NULL,
    status       VARCHAR(20)  NOT NULL,
    CONSTRAINT uk_uploaded_image_image_key UNIQUE (image_key)
);

CREATE INDEX idx_uploaded_image_member_id ON uploaded_image (member_id);
CREATE INDEX idx_uploaded_image_status_created_at ON uploaded_image (status, created_at);

-- 사진 파일 본문. 공용 저장소(S3 등)로 옮기기 전까지 DB 에 둔다
CREATE TABLE image_file
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    image_key    VARCHAR(100) NOT NULL,
    content_type VARCHAR(30)  NOT NULL,
    content      BYTEA        NOT NULL,
    CONSTRAINT uk_image_file_image_key UNIQUE (image_key)
);

-- 게시물 묶음(post, post_image, post_part, post_part_tag) 안에서만 FK 를 둔다
CREATE TABLE post
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP(6) NOT NULL,
    updated_at        TIMESTAMP(6) NOT NULL,
    member_id         BIGINT       NOT NULL,
    owned_car_id      BIGINT       NOT NULL,
    car_model_id      BIGINT       NOT NULL,
    car_generation_id BIGINT       NOT NULL,
    car_trim_id       BIGINT       NOT NULL,
    model_year        INTEGER      NOT NULL,
    build_style       VARCHAR(20)  NOT NULL,
    content           VARCHAR(1000),
    status            VARCHAR(20)  NOT NULL,
    part_count        INTEGER      NOT NULL
);

CREATE INDEX idx_post_member_id ON post (member_id);
CREATE INDEX idx_post_owned_car_id ON post (owned_car_id);
CREATE INDEX idx_post_status_car_model_id ON post (status, car_model_id);

CREATE TABLE post_image
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id       BIGINT       NOT NULL REFERENCES post (id),
    image_key     VARCHAR(100) NOT NULL,
    url           VARCHAR(500) NOT NULL,
    width         INTEGER      NOT NULL,
    height        INTEGER      NOT NULL,
    display_order INTEGER      NOT NULL,
    CONSTRAINT uk_post_image_image_key UNIQUE (image_key)
);

CREATE INDEX idx_post_image_post_id ON post_image (post_id);

-- 게시물에 달린 부품(postPartId). 위시리스트는 이 id 를 담는다
CREATE TABLE post_part
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id       BIGINT      NOT NULL REFERENCES post (id),
    part_id       BIGINT      NOT NULL,
    category      VARCHAR(20) NOT NULL,
    display_order INTEGER     NOT NULL
);

CREATE INDEX idx_post_part_post_id ON post_part (post_id);
CREATE INDEX idx_post_part_part_id ON post_part (part_id);

CREATE TABLE post_part_tag
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_part_id  BIGINT           NOT NULL REFERENCES post_part (id),
    post_image_id BIGINT           NOT NULL REFERENCES post_image (id),
    x             DOUBLE PRECISION NOT NULL,
    y             DOUBLE PRECISION NOT NULL
);

CREATE INDEX idx_post_part_tag_post_part_id ON post_part_tag (post_part_id);
CREATE INDEX idx_post_part_tag_post_image_id ON post_part_tag (post_image_id);

-- post_id, post_author_id 는 목록·담기 수 집계를 위해 담을 때 복사해 둔다. 탈퇴한 회원의 담기는 hidden
CREATE TABLE wishlist_item
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP(6) NOT NULL,
    updated_at     TIMESTAMP(6) NOT NULL,
    member_id      BIGINT       NOT NULL,
    post_part_id   BIGINT       NOT NULL,
    post_id        BIGINT       NOT NULL,
    post_author_id BIGINT       NOT NULL,
    hidden         BOOLEAN      NOT NULL,
    CONSTRAINT uk_wishlist_item_member_id_post_part_id UNIQUE (member_id, post_part_id)
);

CREATE INDEX idx_wishlist_item_post_part_id ON wishlist_item (post_part_id);
CREATE INDEX idx_wishlist_item_post_id ON wishlist_item (post_id);
CREATE INDEX idx_wishlist_item_post_author_id ON wishlist_item (post_author_id);
